party-rails/config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :ratings
  resources :staffs
  resources :services do
    resources :user_services
  end
  devise_for :users

  root to: 'dashboards#dashboard_admin', constraints: RoleConstraint.new(:admin), as: :authenticated_admin #matches this route when the current user is an super admin
  root 'dashboards#dashboard'

  ## API ##
  namespace :api, defaults: { format: "json" } do
  	namespace :v1 do
  		post 'users', to: 'users#register'
  		post 'users/login', to: 'users#login'
      get 'services', to: 'services#index'
      post 'services', to: 'services#new_request'
      post 'ratings', to: 'ratings#new_rating'
  	end
  end
end

party-rails/app/models/staff.rb
class Staff < ApplicationRecord
  belongs_to :user_service
  belongs_to :user
end

party-rails/app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:user_service_id, :user_id)
    end
end

party-rails/app/helpers/staffs_helper.rb
module StaffsHelper
end

party-rails/app/views/staffs/_form.html.erb
<%= form_with(model: staff, local: true) do |form| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_service_id %>
    <%= form.text_field :user_service_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

party-rails/app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

party-rails/app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staffs</h1>

<table>
  <thead>
    <tr>
      <th>User service</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.user_service %></td>
        <td><%= staff.user %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

party-rails/app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Back', staffs_path %>

party-rails/app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User service:</strong>
  <%= @staff.user_service %>
</p>

<p>
  <strong>User:</strong>
  <%= @staff.user %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>