party-rails/config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :ratings
  resources :staffs
  resources :services do
    resources :user_services
  end
  devise_for :users

  root to: 'dashboards#dashboard_admin', constraints: RoleConstraint.new(:admin), as: :authenticated_admin #matches this route when the current user is an super admin
  root 'dashboards#dashboard'

  ## API ##
  namespace :api, defaults: { format: "json" } do
  	namespace :v1 do
  		post 'users', to: 'users#register'
  		post 'users/login', to: 'users#login'
      get 'services', to: 'services#index'
      post 'services', to: 'services#new_request'
      post 'ratings', to: 'ratings#new_rating'
  	end
  end
end

party-rails/app/models/user_service.rb
class UserService < ApplicationRecord
  belongs_to :user
  belongs_to :service
  has_many :users, dependent: :destroy
  has_many :staffs, through: :users
  has_many :ratings, dependent: :destroy

  def score_by_user
  	return ratings.find_by_user_id(user_id).score if ratings.find_by_user_id(user_id).present?
  	"Sin calificación aún"
  end

  def comment_by_user
  	return ratings.find_by_user_id(user_id).comment if ratings.find_by_user_id(user_id).present?
  	"Sin comentario"
  end
end

party-rails/app/controllers/user_services_controller.rb
class UserServicesController < ApplicationController
  before_action :set_user_service, only: [:show, :edit, :update, :destroy]
  before_action :set_service, only: [:index]

  # GET /user_services
  # GET /user_services.json
  def index
    @user_services = @service.user_services
  end

  # GET /user_services/1
  # GET /user_services/1.json
  def show
  end

  # GET /user_services/new
  def new
    @user_service = UserService.new
  end

  # GET /user_services/1/edit
  def edit
  end

  # POST /user_services
  # POST /user_services.json
  def create
    @user_service = UserService.new(user_service_params)

    respond_to do |format|
      if @user_service.save
        format.html { redirect_to @user_service, notice: 'User service was successfully created.' }
        format.json { render :show, status: :created, location: @user_service }
      else
        format.html { render :new }
        format.json { render json: @user_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_services/1
  # PATCH/PUT /user_services/1.json
  def update
    respond_to do |format|
      if @user_service.update(user_service_params)
        format.html { redirect_to @user_service, notice: 'User service was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_service }
      else
        format.html { render :edit }
        format.json { render json: @user_service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_services/1
  # DELETE /user_services/1.json
  def destroy
    @user_service.destroy
    respond_to do |format|
      format.html { redirect_to user_services_url, notice: 'User service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_service
      @user_service = UserService.find(params[:id])
    end

    def set_service
      @service = Service.find(params[:service_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_service_params
      params.require(:user_service).permit(:user_id, :service_id)
    end
end

party-rails/app/helpers/user_services_helper.rb
module UserServicesHelper
end

party-rails/app/views/user_services/_form.html.erb
<%= form_with(model: user_service, local: true) do |form| %>
  <% if user_service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_service.errors.count, "error") %> prohibited this user_service from being saved:</h2>

      <ul>
      <% user_service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :service_id %>
    <%= form.text_field :service_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

party-rails/app/views/user_services/_row.html.erb
<% if can? :read, user_service %>
  <tr id="<%= user_service.id %>">
    <td><%= user_service.user.names %></td>
    <td><%= user_service.score_by_user %></td>
    <td><%= user_service.comment_by_user %></td>
  </tr>
<% end %>

party-rails/app/views/user_services/edit.html.erb
<h1>Editing User Service</h1>

<%= render 'form', user_service: @user_service %>

<%= link_to 'Show', @user_service %> |
<%= link_to 'Back', user_services_path %>

party-rails/app/views/user_services/index.html.erb
<div class="container">
  <div class="row">
    <h2>Servicios solicitados de <%= @service.name %></h2>
    <table class="table">
      <thead>
        <tr>
          <th>Solicitante</th>
          <th>Calificación de usuario</th>
          <th>Comentario</th>
        </tr>
      </thead>
      <tbody>
        <% @user_services.each do |user_service| %>
          <%= render "row", user_service: user_service %>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Regresar", services_path, class: "btn btn-default" %>
  </div>
</div>

party-rails/app/views/user_services/new.html.erb
<h1>New User Service</h1>

<%= render 'form', user_service: @user_service %>

<%= link_to 'Back', user_services_path %>

party-rails/app/views/user_services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_service.user %>
</p>

<p>
  <strong>Service:</strong>
  <%= @user_service.service %>
</p>

<%= link_to 'Edit', edit_user_service_path(@user_service) %> |
<%= link_to 'Back', user_services_path %>