party-rails/config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :ratings
  resources :staffs
  resources :services do
    resources :user_services
  end
  devise_for :users

  root to: 'dashboards#dashboard_admin', constraints: RoleConstraint.new(:admin), as: :authenticated_admin #matches this route when the current user is an super admin
  root 'dashboards#dashboard'

  ## API ##
  namespace :api, defaults: { format: "json" } do
  	namespace :v1 do
  		post 'users', to: 'users#register'
  		post 'users/login', to: 'users#login'
      get 'services', to: 'services#index'
      post 'services', to: 'services#new_request'
      post 'ratings', to: 'ratings#new_rating'
  	end
  end
end

party-rails/app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user_service
  belongs_to :user

  validates :score, presence: true
end

party-rails/app/controllers/api/v1/ratings_controller.rb
module Api::V1
	class RatingsController < ApplicationController

		include Concerns::SkipAuthenticate
    	include Concerns::Authorization

		
		def new_rating
			result = { success: false, status: 400, message: "Calificación exitosa" }
			json_schema = "app/controllers/api/v1/schemas/ratings/new_rating.json"
			begin
				JSON::Validator.validate!(json_schema, params.to_json)

				user_service_id = params[:user_service_id]
				user_service = UserService.find_by_id(user_service_id)

				if user_service.present?
					if user_service.user_id == @current_user.id
						new_rating = Rating.new(user_id: @current_user.id, user_service_id: user_service_id, score: params[:score], comment: params[:comment])
						if new_rating.save
							result[:success] = true
							result[:status] = 201
						else
							result[:message] = "Error al registrar calificación: #{new_rating.errors.full_messages}"
						end
					else
						result[:message] = "Servicio no pertenece a usuario calificador"
					end
				else
					result[:status] = 404
					result[:message] = "Servicio no existe"
				end
			rescue JSON::Schema::ValidationError => e
				result[:message] = e.message
			end

			render json: result
		end

	end
end

party-rails/app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:score, :comment, :user_service_id, :user_id)
    end
end

party-rails/app/helpers/ratings_helper.rb
module RatingsHelper
end

party-rails/app/views/ratings/_form.html.erb
<%= form_with(model: rating, local: true) do |form| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="field">
    <%= form.label :user_service_id %>
    <%= form.text_field :user_service_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

party-rails/app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

party-rails/app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th>Comment</th>
      <th>User service</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.score %></td>
        <td><%= rating.comment %></td>
        <td><%= rating.user_service %></td>
        <td><%= rating.user %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

party-rails/app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Back', ratings_path %>

party-rails/app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @rating.score %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @rating.comment %>
</p>

<p>
  <strong>User service:</strong>
  <%= @rating.user_service %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>