party-rails/config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  resources :ratings
  resources :staffs
  resources :services do
    resources :user_services
  end
  devise_for :users

  root to: 'dashboards#dashboard_admin', constraints: RoleConstraint.new(:admin), as: :authenticated_admin #matches this route when the current user is an super admin
  root 'dashboards#dashboard'

  ## API ##
  namespace :api, defaults: { format: "json" } do
  	namespace :v1 do
  		post 'users', to: 'users#register'
  		post 'users/login', to: 'users#login'
      get 'services', to: 'services#index'
      post 'services', to: 'services#new_request'
      post 'ratings', to: 'ratings#new_rating'
  	end
  end
end

party-rails/app/models/service.rb
class Service < ApplicationRecord
	has_many :user_services, dependent: :destroy
	has_many :services, through: :user_services
	
	scope :actives, -> { where is_active: true }

	def as_json(options={})
		super({except: [:is_active, :created_at, :updated_at]})
	end
end

party-rails/app/controllers/api/v1/services_controller.rb
module Api::V1
	class ServicesController < ApplicationController

		include Concerns::SkipAuthenticate
    	include Concerns::Authorization

		
		def index
			result = { success: true, status: 200, message: "Servicios ofertados" }
			result[:services] = Service.actives
			render json: result
		end

		def new_request
			result = { success: false, status: 400, message: "Solicitud creada correctamente" }
			json_schema = "app/controllers/api/v1/schemas/services/new_request.json"
			begin
				JSON::Validator.validate!(json_schema, params.to_json)

				service_id = params[:service_id]
				service = Service.find_by_id(service_id)

				if service.present?
					new_user_service = UserService.new(service_id: service_id, user_id: @current_user.id)
					if new_user_service.save
						result[:success] = true
						result[:status] = 201
					else
						result[:message] = "Error al registrar solicitud: #{new_user_service.errors.full_messages}"
					end
				else
					result[:status] = 404
					result[:message] = "Servicio no existe"
				end
			rescue JSON::Schema::ValidationError => e
				result[:message] = e.message
			end

			render json: result
		end

	end
end

party-rails/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.js { flash[:notice] = 'Servicio creado correctamente.' }
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.js {}
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.js { flash[:notice] = 'Servicio actualizado correctamente.' }
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.js {}
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.js { flash[:notice] = 'Servicio eliminado correctamente.' }
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :description, :is_active)
    end
end

party-rails/app/helpers/services_helper.rb
module ServicesHelper
end

party-rails/app/views/services/_form.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="customerModalLabel"><%= title %></h4>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<%= form_with(model: service, local: false) do |form| %>
  <div class="modal-body">
    <div class="form-group">
      <label for="location_name" class="form-control-label">Nombre:</label>
      <%= form.text_field :name, class:'form-control', autofocus: true, placeholder: "Nombre", maxlength: 55 %>
    </div>
    <div class="form-group">
      <label for="service[description]" class="form-control-label">Descripción:</label>
      <%= form.text_area :description, class:'form-control', placeholder: "Descripción", maxlength: 255, rows: 8, style: "resize: none;" %>
    </div>
    <div class="custom-control custom-switch">
      <%= form.check_box :is_active, class: "custom-control-input", id: "switch1" %>
      <label class="custom-control-label" for="switch1">Activo</label>
    </div>
    <span id="span_form" style="color: red;"></span>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" onclick="dismissServiceModal()">Cancelar</button>
    <button type="submit" class="btn btn-primary" onclick="return validateServiceForm()">Guardar</button>
  </div>
<% end %>

party-rails/app/views/services/_row.html.erb
<% if can? :read, service %>
  <tr id="<%= service.id %>">
    <td><%= service.name %></td>
    <td><%= service.description %></td>
    <td><%= yes_no(service.is_active) %></td>
    <td><%= link_to "Solicitudes", service_user_services_path(service) %></td>
    <% if can? :update, service %>
    	<td><%= link_to "Editar", edit_service_path(service), remote: true, "data-toggle" => "modal", "data-target" => "#serviceModal" %></td>
    <% end %>
    <% if can? :destroy, service and current_user.admin? %>
    	<td><%= link_to 'Eliminar', service, method: :delete, remote: true, data: {confirm: 'Eliminar servicio'} %></td>
    <% end %>
  </tr>
<% end %>

party-rails/app/views/services/create.js.erb
<% if @service.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('table tbody').append('<%= j render "row", service: @service %>');
  $('.flash_wrapper').html('<%= j render "layouts/messages" %>');
  $('#serviceModal').modal('hide');
<% else %>
  // show first error
  alert('<%= @service.errors.full_messages[0] %>');
<% end %>

party-rails/app/views/services/destroy.js.erb
<% if @service.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $("tr#<%= @service.id %>").remove();
  $('.flash_wrapper').html('<%= j render "layouts/messages" %>');
<% else %>
  // show first error
  alert('<%= @service.errors.full_messages[0] %>');
<% end %>

party-rails/app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

party-rails/app/views/services/edit.js.erb
$('#content-service-modal').html('<%= j render "form", title: "Editar servicio", service: @service %>');
$('#serviceModal').modal('show');

party-rails/app/views/services/index.html.erb
<div class="container">
  <div class="row">
    <h2>Servicios ofertados</h2>
    <table class="table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Descripción</th>
          <th>Activo</th>
          <th colspan="4"></th>
        </tr>
      </thead>
      <tbody>
        <% @services.each do |service| %>
          <%= render "row", service: service %>
        <% end %>
      </tbody>
    </table>
    <br>

    <% if can? :create, Service %>
      <%= link_to "Nuevo servicio", new_service_path, remote: true, class: "btn btn-primary", data: { toggle: "modal", target: "serviceModal"} %>
    <% end %>

    <% if can? :create, Service or can? :update, Service %>
      <div class="modal fade" id="serviceModal" tabindex="-1" role="dialog" aria-labelledby="serviceModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content" id="content-service-modal">
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

party-rails/app/views/services/new.html.erb
<h1>New Service</h1>

<%= render 'form', service: @service %>

<%= link_to 'Back', services_path %>

party-rails/app/views/services/new.js.erb
$('#content-service-modal').html('<%= j render "form", title: "Nuevo servicio", service: @service %>');
$('#serviceModal').modal('show');

party-rails/app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @service.description %>
</p>

<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>

party-rails/app/views/services/update.js.erb
<% if @service.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $("tr#<%= @service.id %>").replaceWith('<%= j render "row", service: @service %>');
  $('.flash_wrapper').html('<%= j render "layouts/messages" %>');
  $('#serviceModal').modal('hide');
<% else %>
  // show first error
  alert('<%= @service.errors.full_messages[0] %>');
<% end %>